[package]
name = "cxx-crc32fast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.4"
cxx = "1"

[build-dependencies]
cxx-build = "1"
