[package]
name = "cxx-pretty-json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde-transcode = "1.1.1"
serde_json = "1.0.114"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
